### ISSUE TITLE
Officially support Windows

### ISSUE THREAD

**Issue by moorepants** [csu-hmc/opty#89]
Now that there is a conda forge build of ipopt for windows:

https://github.com/conda-forge/ipopt-feedstock/pull/47

We can more easily support windows. We could also mimic the current cyipopt CI setup to download a IPOPT binary if that is useful.

- [x] Get IPOPT support in cyipopt for the conda forge packaged IPOPT for Windows.
- [x] Setup CI for windows builds (appveyor, or maybe its time to learn GIthub Actions)

**Comment by ashander** [comment]
- [ ]  solve file permissions issues* for development

* At least on my setup I get file permissions issues from tempdir (e.g as used in [utils](ttps://github.com/ashander/opty/blob/44747024a25687c57e8f693ce1826beeb688c6c8/opty/utils.py#L232) ) because the security setup for tempfile I suppose. To fully fix seems likely we would need to induce dependency on pywin32. 

The good news that issue only comes up in development (running nose) but can be solved for actually using opty by setting an appropriate environment variable for location of temp files (eg $TMPDIR https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir)

**Comment by moorepants** [comment]
I use pywin32 on PyDy for the same reason. Maybe that's the simplest fix.

**Comment by moorepants** [comment]
dev version will install and run on windows. Just need to make a point release for pypi and conda-forge.
